### ISSUE TITLE
Odd indents on bufferEnter and << >>?

### ISSUE THREAD

**Issue by aqui8** [clojure-vim/nvim-parinfer.js#23] opened 2016-09-22 09:55 UTC
I've tried this with all my other plugins and settings turned off. (ie testing with just 'snoe/nvim-parinfer.js' and 'neovim/node-host').

The first indent seems to indent only one space, then the next ones indent 2 spaces. So you have this odd situation where you have a 3 space indent.

On `bufferEnter` (one space before `:description`):

```
(defproject graphic-design "0.1.0-SNAPSHOT"
 :description "FIXME: write description"
```

after `>>` (three spaces before `:description`):

```
(defproject graphic-design "0.1.0-SNAPSHOT"
   :description "FIXME: write description"
```

Anyone else getting this?

**Comment by snoe** [comment] 2016-10-07 19:48
@anthoq88 
This is by design, the plugin shifts only to the next structural change column from the line above and then falls back to vim's default tabstop if there are no more structural changes on the line above.

If you want proper indentation look at running https://github.com/guns/vim-clojure-static or https://github.com/weavejester/cljfmt 

So with cursor at `|`, `>>` will turn this

```clojure
(defproject graphic-design "0.1.0-SNAPSHOT")
|:description
```

into

```clojure
(defproject graphic-design "0.1.0-SNAPSHOT"
 |:description)
```

Since there are no more parens on the `defproject` line another shift simply moves two spaces

```clojure
(defproject graphic-design "0.1.0-SNAPSHOT"
   |:description)
```

**Comment by bugeats** [comment] 2016-10-24 17:42
> This is by design, the plugin shifts only to the next structural change column from the line above and then falls back to vim's default tabstop if there are no more structural changes on the line above.

I having trouble identifying what a **structural change column** is. It's nowhere in the parinfer docs. 

Here's my current behavior with `tabstop` and `shiftwidth` both set to `2` (where `|` is the cursor):

```clojure
 (defn inch [n])
|(str n "in")
```

`>>`:

```clojure
 (defn inch [n])
  (|str n "in")
```

`>>`:

```clojure
(defn inch [n
            (|str n "in")])
```

It's hard to see why this would be by design with the indent behavior works as expected in insert mode.

**Comment by snoe** [comment] 2016-10-24 19:19
@bugeats https://github.com/shaunlebron/parinfer/tree/master/lib look for "tabStops" 

>  We identify tab stops at relevant open-parens

I'm open to some better dumb default that might take `shiftwidth` into account - but I also feel that parinfer's place is to syntactically build s-expressions trees. Implementing something like https://github.com/bbatsov/clojure-style-guide is probably better done by running a formatting plugin after parinfer's tree changes.

https://github.com/shaunlebron/parinfer/issues/59 goes into parinfer's approach to this problem

**Comment by bugeats** [comment] 2016-10-24 19:29
Ah, yes I understand now thanks. The separation of concerns makes sense to me. Given that, I'd say all we need for this project is a working example in the README of running a formatter after the shift. I'd take a crack at it, but my vim-fu is pretty weak.

**Comment by DogLooksGood** [comment] 2016-10-27 03:54
@bugeats vim-sexp provide `=-` for indent current top-sexp.

**Comment by bugeats** [comment] 2016-10-27 03:59
Thanks. I'm now using [venantius/vim-cljfmt](https://github.com/venantius/vim-cljfmt) to re-format on write. I'm super happy with my setup right now.

**Comment by snoe** [comment] 2017-02-15 05:02
I'm going to close this, I think clojure-vim's goal is to bring a cohesive set of plugins for clojure + vim and I'd rather put the documentation on indenting clojure code beyond parinfer at a higher level.

**Closed by snoe** 2017-02-15 05:02 UTC
